kube_master_imgs:
    - kube-controller-manager-amd64:{{ kube_version }}
    - kube-scheduler-amd64:{{ kube_version }}
    - kube-apiserver-amd64:{{ kube_version }}
    - kube-proxy-amd64:{{ kube_version }}
    - pause-amd64:3.1
    - coredns:1.1.3
    - etcd-amd64:3.2.18
    - kubernetes-dashboard-amd64:v1.8.3
#    - quay.io/calico/node:v2.6.5
#    - quay.io/calico/kube-controllers:v1.0.2
#    - quay.io/calico/cni:v1.11.2
#    - quay.io/coreos/etcd:v3.1.10